// Adapted from Dan Shiffman, natureofcode.com
// Visualize the distribution of numbers generated by 
// the random function in p5js

// Set initial variables and colors
let randomCounts = [];
let rectWidth;

function setup() {
	createCanvas(windowWidth, windowHeight);

	for (let i = 0; i < 20; i++) {
	    randomCounts[i] = 0;
	    rectWidth = floor(width/randomCounts.length);
	    console.log("rectWidth["+i+"] = "+rectWidth);
		noStroke();
	}
}


// Animate the distribution of random numbers over time
function draw() {
  background(255, 255, 255);
 
  let index = floor(random(randomCounts.length));
  randomCounts[index]++;
  
  for (let i = 0; i < randomCounts.length; i++) {
    fill(173, 173, 173);
    rect(i*rectWidth,
        height-randomCounts[i],
        rectWidth-1,
        randomCounts[i]);
    fill(0, 0, 0);
    text(i, i*rectWidth+3, height-10);
  }
}
